### PR TITLE
Add support for pre-recorded output

### PR DESCRIPTION
**Pull request by dirkschumacher**
This adds a special key that can be used to allow pre-recorded output in the runner.

### CODE REVIEW

**Review by larsbeck — APPROVED** [review]

**Review by merschformann — APPROVED** [review]

**Comment by dirkschumacher** [comment]
@merschformann @larsbeck any ideas on the name? `$recorded_output`, `_recorded_output`, `$pre_recorded_output`, `$output`. etc. etc.

**Comment by larsbeck** [comment]
> @merschformann @larsbeck any ideas on the name? `$recorded_output`, `_recorded_output`, `$pre_recorded_output`, `$output`. etc. etc.

`__recorded_output` is good for me.

**Comment by merschformann** [comment]
I thought the reserved field was `__recorded_output`. I don't have a strong opinion on the name. Is there any kind of convention around JSON? The leading double `_` may be easy to get wrong, but also not a real issue. Coming from Python one may take it as a _really_ private field. :relaxed:

**Comment by dirkschumacher** [comment]
Yeah I am unsure. My intent was to clearly distinguish it from any user defined keys. `$recorded_output` might also be a good option.

**Comment by merschformann** [comment]
I prefer the `_`, but that may just be my Python side. The `$` already has a different meaning in JSON context, right? I would avoid it, if that is the case. Doesn't it refer to the root or something?

**Review by sebastian-quintero — APPROVED** [review]
LGTM

**Pull request merged**
