### PR TITLE
Fix some typos in the templates

### PR DESCRIPTION
**Pull request by muellerd**
Fixed some minor typos in comments of our templates

### CODE REVIEW

**Review by nilsbeck — DISMISSED** [review]
Thanks for fixing this!

**Review by dirkschumacher — DISMISSED** [review]

**Comment by dirkschumacher** [comment]
You need to amend your commit and sign it.  Then force push a history just with signed commits.

**Review by sebastian-quintero — DISMISSED** [review]

**Comment by muellerd** [comment]
Need another review after signing my commits. Thank you!

**Review by nilsbeck — APPROVED** [review]

**Review by merschformann — APPROVED** [review]
:rocket:

**Pull request merged**
